/*
 * DropBearTable
 * This is a sample server API for a new restaurant service.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlegresl@myune.edu.au
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {InlineResponse4012Errors} from './InlineResponse4012Errors';

/**
 * The InlineResponse4012 model module.
 * @module model/InlineResponse4012
 * @version 1.0.0
 */
export class InlineResponse4012 {
  /**
   * Constructs a new <code>InlineResponse4012</code>.
   * @alias module:model/InlineResponse4012
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>InlineResponse4012</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse4012} obj Optional instance to populate.
   * @return {module:model/InlineResponse4012} The populated <code>InlineResponse4012</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InlineResponse4012();
      if (data.hasOwnProperty('errors'))
        obj.errors = InlineResponse4012Errors.constructFromObject(data['errors']);
    }
    return obj;
  }
}

/**
 * @member {module:model/InlineResponse4012Errors} errors
 */
InlineResponse4012.prototype.errors = undefined;

