/*
 * DropBearTable
 * This is a sample server API for a new restaurant service.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlegresl@myune.edu.au
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The InlineResponse401Errors model module.
 * @module model/InlineResponse401Errors
 * @version 1.0.0
 */
export class InlineResponse401Errors {
  /**
   * Constructs a new <code>InlineResponse401Errors</code>.
   * @alias module:model/InlineResponse401Errors
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>InlineResponse401Errors</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse401Errors} obj Optional instance to populate.
   * @return {module:model/InlineResponse401Errors} The populated <code>InlineResponse401Errors</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InlineResponse401Errors();
      if (data.hasOwnProperty('confirmation'))
        obj.confirmation = ApiClient.convertToType(data['confirmation'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} confirmation
 */
InlineResponse401Errors.prototype.confirmation = undefined;

