/*
 * DropBearTable
 * This is a sample server API for a new restaurant service.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlegresl@myune.edu.au
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The InlineResponse201Data model module.
 * @module model/InlineResponse201Data
 * @version 1.0.0
 */
export class InlineResponse201Data {
  /**
   * Constructs a new <code>InlineResponse201Data</code>.
   * @alias module:model/InlineResponse201Data
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>InlineResponse201Data</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse201Data} obj Optional instance to populate.
   * @return {module:model/InlineResponse201Data} The populated <code>InlineResponse201Data</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InlineResponse201Data();
      if (data.hasOwnProperty('_id'))
        obj.id = ApiClient.convertToType(data['_id'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
InlineResponse201Data.prototype.id = undefined;

/**
 * @member {String} name
 */
InlineResponse201Data.prototype.name = undefined;

