/*
 * DropBearTable
 * This is a sample server API for a new restaurant service.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlegresl@myune.edu.au
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The LoginGuestBody model module.
 * @module model/LoginGuestBody
 * @version 1.0.0
 */
export class LoginGuestBody {
  /**
   * Constructs a new <code>LoginGuestBody</code>.
   * @alias module:model/LoginGuestBody
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>LoginGuestBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/LoginGuestBody} obj Optional instance to populate.
   * @return {module:model/LoginGuestBody} The populated <code>LoginGuestBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new LoginGuestBody();
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('password'))
        obj.password = ApiClient.convertToType(data['password'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} email
 */
LoginGuestBody.prototype.email = undefined;

/**
 * @member {String} password
 */
LoginGuestBody.prototype.password = undefined;

