/*
 * DropBearTable
 * This is a sample server API for a new restaurant service.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlegresl@myune.edu.au
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The ReservationsReservationIdBody model module.
 * @module model/ReservationsReservationIdBody
 * @version 1.0.0
 */
export class ReservationsReservationIdBody {
  /**
   * Constructs a new <code>ReservationsReservationIdBody</code>.
   * @alias module:model/ReservationsReservationIdBody
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ReservationsReservationIdBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ReservationsReservationIdBody} obj Optional instance to populate.
   * @return {module:model/ReservationsReservationIdBody} The populated <code>ReservationsReservationIdBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ReservationsReservationIdBody();
      if (data.hasOwnProperty('date'))
        obj._date = ApiClient.convertToType(data['date'], 'String');
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} _date
 */
ReservationsReservationIdBody.prototype._date = undefined;

/**
 * @member {String} status
 */
ReservationsReservationIdBody.prototype.status = undefined;

