/*
 * DropBearTable
 * This is a sample server API for a new restaurant service.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlegresl@myune.edu.au
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The UserIdReservationsBody model module.
 * @module model/UserIdReservationsBody
 * @version 1.0.0
 */
export class UserIdReservationsBody {
  /**
   * Constructs a new <code>UserIdReservationsBody</code>.
   * @alias module:model/UserIdReservationsBody
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>UserIdReservationsBody</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UserIdReservationsBody} obj Optional instance to populate.
   * @return {module:model/UserIdReservationsBody} The populated <code>UserIdReservationsBody</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UserIdReservationsBody();
      if (data.hasOwnProperty('restaurant'))
        obj.restaurant = ApiClient.convertToType(data['restaurant'], 'String');
      if (data.hasOwnProperty('date'))
        obj._date = ApiClient.convertToType(data['date'], 'String');
      if (data.hasOwnProperty('time'))
        obj.time = ApiClient.convertToType(data['time'], 'String');
      if (data.hasOwnProperty('guests'))
        obj.guests = ApiClient.convertToType(data['guests'], 'String');
      if (data.hasOwnProperty('mobile'))
        obj.mobile = ApiClient.convertToType(data['mobile'], 'Number');
      if (data.hasOwnProperty('requests'))
        obj.requests = ApiClient.convertToType(data['requests'], 'Number');
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} restaurant
 */
UserIdReservationsBody.prototype.restaurant = undefined;

/**
 * @member {String} _date
 */
UserIdReservationsBody.prototype._date = undefined;

/**
 * @member {String} time
 */
UserIdReservationsBody.prototype.time = undefined;

/**
 * @member {String} guests
 */
UserIdReservationsBody.prototype.guests = undefined;

/**
 * @member {Number} mobile
 */
UserIdReservationsBody.prototype.mobile = undefined;

/**
 * @member {Number} requests
 */
UserIdReservationsBody.prototype.requests = undefined;

/**
 * @member {String} status
 */
UserIdReservationsBody.prototype.status = undefined;

