/*
 * DropBearTable
 * This is a sample server API for a new restaurant service.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlegresl@myune.edu.au
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from "../ApiClient";
import {Body} from '../model/Body';
import {InlineResponse200} from '../model/InlineResponse200';
import {InlineResponse2001} from '../model/InlineResponse2001';
import {InlineResponse2002} from '../model/InlineResponse2002';
import {InlineResponse201} from '../model/InlineResponse201';
import {InlineResponse401} from '../model/InlineResponse401';
import {InlineResponse4011} from '../model/InlineResponse4011';
import {InlineResponse4012} from '../model/InlineResponse4012';

/**
* Apirestaurant service.
* @module api/ApirestaurantApi
* @version 1.0.0
*/
export class ApirestaurantApi {

    /**
    * Constructs a new ApirestaurantApi. 
    * @alias module:api/ApirestaurantApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the restaurantIdGET operation.
     * @callback moduleapi/ApirestaurantApi~restaurantIdGETCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse2001{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get details of a resuarant
     * @param {String} restaurantId ID of restaurant to return
     * @param {module:api/ApirestaurantApi~restaurantIdGETCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    restaurantIdGET(restaurantId, callback) {
      
      let postBody = null;
      // verify the required parameter 'restaurantId' is set
      if (restaurantId === undefined || restaurantId === null) {
        throw new Error("Missing the required parameter 'restaurantId' when calling restaurantIdGET");
      }

      let pathParams = {
        'restaurantId': restaurantId
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = InlineResponse2001;

      return this.apiClient.callApi(
        '/{restaurantId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the restaurantIdScheduleGET operation.
     * @callback moduleapi/ApirestaurantApi~restaurantIdScheduleGETCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse2002{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get a restaurants schedule
     * @param {String} restaurantId ID of restaurant to return
     * @param {module:api/ApirestaurantApi~restaurantIdScheduleGETCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    restaurantIdScheduleGET(restaurantId, callback) {
      
      let postBody = null;
      // verify the required parameter 'restaurantId' is set
      if (restaurantId === undefined || restaurantId === null) {
        throw new Error("Missing the required parameter 'restaurantId' when calling restaurantIdScheduleGET");
      }

      let pathParams = {
        'restaurantId': restaurantId
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = InlineResponse2002;

      return this.apiClient.callApi(
        '/{restaurantId}/schedule', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the rootGET operation.
     * @callback moduleapi/ApirestaurantApi~rootGETCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse200{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get all restaurants
     * @param {module:api/ApirestaurantApi~rootGETCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    rootGET(callback) {
      
      let postBody = null;

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = InlineResponse200;

      return this.apiClient.callApi(
        '/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the rootPOST operation.
     * @callback moduleapi/ApirestaurantApi~rootPOSTCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse201{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Add an new restaurant
     * @param {module:model/Body} body Restaurant object that needs to be saved to database
     * @param {module:api/ApirestaurantApi~rootPOSTCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    rootPOST(body, callback) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling rootPOST");
      }

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = InlineResponse201;

      return this.apiClient.callApi(
        '/', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}