/*
 * DropBearTable
 * This is a sample server API for a new restaurant service.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlegresl@myune.edu.au
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from "../ApiClient";
import {InlineResponse200} from '../model/InlineResponse200';
import {InlineResponse401} from '../model/InlineResponse401';

/**
* Apisearch service.
* @module api/ApisearchApi
* @version 1.0.0
*/
export class ApisearchApi {

    /**
    * Constructs a new ApisearchApi. 
    * @alias module:api/ApisearchApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the dateTimeGuestsGET operation.
     * @callback moduleapi/ApisearchApi~dateTimeGuestsGETCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse200{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Search based on date, time and keyword
     * @param {String} _date date for search
     * @param {String} time time for search
     * @param {String} guests guests for search
     * @param {module:api/ApisearchApi~dateTimeGuestsGETCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    dateTimeGuestsGET(_date, time, guests, callback) {
      
      let postBody = null;
      // verify the required parameter '_date' is set
      if (_date === undefined || _date === null) {
        throw new Error("Missing the required parameter '_date' when calling dateTimeGuestsGET");
      }
      // verify the required parameter 'time' is set
      if (time === undefined || time === null) {
        throw new Error("Missing the required parameter 'time' when calling dateTimeGuestsGET");
      }
      // verify the required parameter 'guests' is set
      if (guests === undefined || guests === null) {
        throw new Error("Missing the required parameter 'guests' when calling dateTimeGuestsGET");
      }

      let pathParams = {
        'date': _date,'time': time,'guests': guests
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = InlineResponse200;

      return this.apiClient.callApi(
        '/{date}/{time}/{guests}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the keywordGET operation.
     * @callback moduleapi/ApisearchApi~keywordGETCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse200{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Search based on keyword
     * @param {String} keyword keyword for search
     * @param {module:api/ApisearchApi~keywordGETCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    keywordGET(keyword, callback) {
      
      let postBody = null;
      // verify the required parameter 'keyword' is set
      if (keyword === undefined || keyword === null) {
        throw new Error("Missing the required parameter 'keyword' when calling keywordGET");
      }

      let pathParams = {
        'keyword': keyword
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = InlineResponse200;

      return this.apiClient.callApi(
        '/{keyword}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}