/*
 * DropBearTable
 * This is a sample server API for a new restaurant service.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlegresl@myune.edu.au
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from './ApiClient';
import {Body} from './model/Body';
import {GuestreservationBody} from './model/GuestreservationBody';
import {InlineResponse200} from './model/InlineResponse200';
import {InlineResponse2001} from './model/InlineResponse2001';
import {InlineResponse2002} from './model/InlineResponse2002';
import {InlineResponse2002Data} from './model/InlineResponse2002Data';
import {InlineResponse2003} from './model/InlineResponse2003';
import {InlineResponse2004} from './model/InlineResponse2004';
import {InlineResponse201} from './model/InlineResponse201';
import {InlineResponse2011} from './model/InlineResponse2011';
import {InlineResponse2012} from './model/InlineResponse2012';
import {InlineResponse201Data} from './model/InlineResponse201Data';
import {InlineResponse401} from './model/InlineResponse401';
import {InlineResponse4011} from './model/InlineResponse4011';
import {InlineResponse4011Errors} from './model/InlineResponse4011Errors';
import {InlineResponse4012} from './model/InlineResponse4012';
import {InlineResponse4012Errors} from './model/InlineResponse4012Errors';
import {InlineResponse401Errors} from './model/InlineResponse401Errors';
import {LoginBody} from './model/LoginBody';
import {LoginGuestBody} from './model/LoginGuestBody';
import {ReservationsReservationIdBody} from './model/ReservationsReservationIdBody';
import {SignupBody} from './model/SignupBody';
import {UserIdReservationsBody} from './model/UserIdReservationsBody';
import {ApirestaurantApi} from './api/ApirestaurantApi';
import {ApisearchApi} from './api/ApisearchApi';
import {ApiuserApi} from './api/ApiuserApi';

/**
* This_is_a_sample_server_API_for_a_new_restaurant_service_.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var DropBearTable = require('index'); // See note below*.
* var xxxSvc = new DropBearTable.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new DropBearTable.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new DropBearTable.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new DropBearTable.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Body model constructor.
     * @property {module:model/Body}
     */
    Body,

    /**
     * The GuestreservationBody model constructor.
     * @property {module:model/GuestreservationBody}
     */
    GuestreservationBody,

    /**
     * The InlineResponse200 model constructor.
     * @property {module:model/InlineResponse200}
     */
    InlineResponse200,

    /**
     * The InlineResponse2001 model constructor.
     * @property {module:model/InlineResponse2001}
     */
    InlineResponse2001,

    /**
     * The InlineResponse2002 model constructor.
     * @property {module:model/InlineResponse2002}
     */
    InlineResponse2002,

    /**
     * The InlineResponse2002Data model constructor.
     * @property {module:model/InlineResponse2002Data}
     */
    InlineResponse2002Data,

    /**
     * The InlineResponse2003 model constructor.
     * @property {module:model/InlineResponse2003}
     */
    InlineResponse2003,

    /**
     * The InlineResponse2004 model constructor.
     * @property {module:model/InlineResponse2004}
     */
    InlineResponse2004,

    /**
     * The InlineResponse201 model constructor.
     * @property {module:model/InlineResponse201}
     */
    InlineResponse201,

    /**
     * The InlineResponse2011 model constructor.
     * @property {module:model/InlineResponse2011}
     */
    InlineResponse2011,

    /**
     * The InlineResponse2012 model constructor.
     * @property {module:model/InlineResponse2012}
     */
    InlineResponse2012,

    /**
     * The InlineResponse201Data model constructor.
     * @property {module:model/InlineResponse201Data}
     */
    InlineResponse201Data,

    /**
     * The InlineResponse401 model constructor.
     * @property {module:model/InlineResponse401}
     */
    InlineResponse401,

    /**
     * The InlineResponse4011 model constructor.
     * @property {module:model/InlineResponse4011}
     */
    InlineResponse4011,

    /**
     * The InlineResponse4011Errors model constructor.
     * @property {module:model/InlineResponse4011Errors}
     */
    InlineResponse4011Errors,

    /**
     * The InlineResponse4012 model constructor.
     * @property {module:model/InlineResponse4012}
     */
    InlineResponse4012,

    /**
     * The InlineResponse4012Errors model constructor.
     * @property {module:model/InlineResponse4012Errors}
     */
    InlineResponse4012Errors,

    /**
     * The InlineResponse401Errors model constructor.
     * @property {module:model/InlineResponse401Errors}
     */
    InlineResponse401Errors,

    /**
     * The LoginBody model constructor.
     * @property {module:model/LoginBody}
     */
    LoginBody,

    /**
     * The LoginGuestBody model constructor.
     * @property {module:model/LoginGuestBody}
     */
    LoginGuestBody,

    /**
     * The ReservationsReservationIdBody model constructor.
     * @property {module:model/ReservationsReservationIdBody}
     */
    ReservationsReservationIdBody,

    /**
     * The SignupBody model constructor.
     * @property {module:model/SignupBody}
     */
    SignupBody,

    /**
     * The UserIdReservationsBody model constructor.
     * @property {module:model/UserIdReservationsBody}
     */
    UserIdReservationsBody,

    /**
    * The ApirestaurantApi service constructor.
    * @property {module:api/ApirestaurantApi}
    */
    ApirestaurantApi,

    /**
    * The ApisearchApi service constructor.
    * @property {module:api/ApisearchApi}
    */
    ApisearchApi,

    /**
    * The ApiuserApi service constructor.
    * @property {module:api/ApiuserApi}
    */
    ApiuserApi
};
