/*
 * DropBearTable
 * This is a sample server API for a new restaurant service.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlegresl@myune.edu.au
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DropBearTable);
  }
}(this, function(expect, DropBearTable) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Body', function() {
      beforeEach(function() {
        instance = new DropBearTable.Body();
      });

      it('should create an instance of Body', function() {
        // TODO: update the code to test Body
        expect(instance).to.be.a(DropBearTable.Body);
      });

      it('should have the property name (base name: "name")', function() {
        // TODO: update the code to test the property name
        expect(instance).to.have.property('name');
        // expect(instance.name).to.be(expectedValueLiteral);
      });

      it('should have the property cuisine (base name: "cuisine")', function() {
        // TODO: update the code to test the property cuisine
        expect(instance).to.have.property('cuisine');
        // expect(instance.cuisine).to.be(expectedValueLiteral);
      });

      it('should have the property openTime (base name: "openTime")', function() {
        // TODO: update the code to test the property openTime
        expect(instance).to.have.property('openTime');
        // expect(instance.openTime).to.be(expectedValueLiteral);
      });

      it('should have the property closeTime (base name: "closeTime")', function() {
        // TODO: update the code to test the property closeTime
        expect(instance).to.have.property('closeTime');
        // expect(instance.closeTime).to.be(expectedValueLiteral);
      });

      it('should have the property seatingInterval (base name: "seatingInterval")', function() {
        // TODO: update the code to test the property seatingInterval
        expect(instance).to.have.property('seatingInterval');
        // expect(instance.seatingInterval).to.be(expectedValueLiteral);
      });

      it('should have the property tableCapacityPerInterval (base name: "tableCapacityPerInterval")', function() {
        // TODO: update the code to test the property tableCapacityPerInterval
        expect(instance).to.have.property('tableCapacityPerInterval');
        // expect(instance.tableCapacityPerInterval).to.be(expectedValueLiteral);
      });

      it('should have the property info (base name: "info")', function() {
        // TODO: update the code to test the property info
        expect(instance).to.have.property('info');
        // expect(instance.info).to.be(expectedValueLiteral);
      });

      it('should have the property image (base name: "image")', function() {
        // TODO: update the code to test the property image
        expect(instance).to.have.property('image');
        // expect(instance.image).to.be(expectedValueLiteral);
      });

    });
  });

}));
