/*
 * DropBearTable
 * This is a sample server API for a new restaurant service.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlegresl@myune.edu.au
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DropBearTable);
  }
}(this, function(expect, DropBearTable) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('InlineResponse2002', function() {
      beforeEach(function() {
        instance = new DropBearTable.InlineResponse2002();
      });

      it('should create an instance of InlineResponse2002', function() {
        // TODO: update the code to test InlineResponse2002
        expect(instance).to.be.a(DropBearTable.InlineResponse2002);
      });

      it('should have the property data (base name: "data")', function() {
        // TODO: update the code to test the property data
        expect(instance).to.have.property('data');
        // expect(instance.data).to.be(expectedValueLiteral);
      });

      it('should have the property confirmation (base name: "confirmation")', function() {
        // TODO: update the code to test the property confirmation
        expect(instance).to.have.property('confirmation');
        // expect(instance.confirmation).to.be(expectedValueLiteral);
      });

      it('should have the property msg (base name: "msg")', function() {
        // TODO: update the code to test the property msg
        expect(instance).to.have.property('msg');
        // expect(instance.msg).to.be(expectedValueLiteral);
      });

    });
  });

}));
