/*
 * DropBearTable
 * This is a sample server API for a new restaurant service.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlegresl@myune.edu.au
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DropBearTable);
  }
}(this, function(expect, DropBearTable) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('UserIdReservationsBody', function() {
      beforeEach(function() {
        instance = new DropBearTable.UserIdReservationsBody();
      });

      it('should create an instance of UserIdReservationsBody', function() {
        // TODO: update the code to test UserIdReservationsBody
        expect(instance).to.be.a(DropBearTable.UserIdReservationsBody);
      });

      it('should have the property restaurant (base name: "restaurant")', function() {
        // TODO: update the code to test the property restaurant
        expect(instance).to.have.property('restaurant');
        // expect(instance.restaurant).to.be(expectedValueLiteral);
      });

      it('should have the property _date (base name: "date")', function() {
        // TODO: update the code to test the property _date
        expect(instance).to.have.property('_date');
        // expect(instance._date).to.be(expectedValueLiteral);
      });

      it('should have the property time (base name: "time")', function() {
        // TODO: update the code to test the property time
        expect(instance).to.have.property('time');
        // expect(instance.time).to.be(expectedValueLiteral);
      });

      it('should have the property guests (base name: "guests")', function() {
        // TODO: update the code to test the property guests
        expect(instance).to.have.property('guests');
        // expect(instance.guests).to.be(expectedValueLiteral);
      });

      it('should have the property mobile (base name: "mobile")', function() {
        // TODO: update the code to test the property mobile
        expect(instance).to.have.property('mobile');
        // expect(instance.mobile).to.be(expectedValueLiteral);
      });

      it('should have the property requests (base name: "requests")', function() {
        // TODO: update the code to test the property requests
        expect(instance).to.have.property('requests');
        // expect(instance.requests).to.be(expectedValueLiteral);
      });

      it('should have the property status (base name: "status")', function() {
        // TODO: update the code to test the property status
        expect(instance).to.have.property('status');
        // expect(instance.status).to.be(expectedValueLiteral);
      });

    });
  });

}));
