/*
 * DropBearTable
 * This is a sample server API for a new restaurant service.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlegresl@myune.edu.au
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DropBearTable);
  }
}(this, function(expect, DropBearTable) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DropBearTable.ApirestaurantApi();
  });

  describe('(package)', function() {
    describe('ApirestaurantApi', function() {
      describe('restaurantIdGET', function() {
        it('should call restaurantIdGET successfully', function(done) {
          // TODO: uncomment, update parameter values for restaurantIdGET call and complete the assertions
          /*

          instance.restaurantIdGET(restaurantId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(DropBearTable.InlineResponse2001);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('restaurantIdScheduleGET', function() {
        it('should call restaurantIdScheduleGET successfully', function(done) {
          // TODO: uncomment, update parameter values for restaurantIdScheduleGET call and complete the assertions
          /*

          instance.restaurantIdScheduleGET(restaurantId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(DropBearTable.InlineResponse2002);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('rootGET', function() {
        it('should call rootGET successfully', function(done) {
          // TODO: uncomment rootGET call and complete the assertions
          /*

          instance.rootGET(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(DropBearTable.InlineResponse200);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('rootPOST', function() {
        it('should call rootPOST successfully', function(done) {
          // TODO: uncomment, update parameter values for rootPOST call and complete the assertions
          /*

          instance.rootPOST(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(DropBearTable.InlineResponse201);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
