/*
 * DropBearTable
 * This is a sample server API for a new restaurant service.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: jlegresl@myune.edu.au
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.27
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DropBearTable);
  }
}(this, function(expect, DropBearTable) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DropBearTable.ApiuserApi();
  });

  describe('(package)', function() {
    describe('ApiuserApi', function() {
      describe('guestReservationPOST', function() {
        it('should call guestReservationPOST successfully', function(done) {
          // TODO: uncomment, update parameter values for guestReservationPOST call and complete the assertions
          /*

          instance.guestReservationPOST(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(DropBearTable.InlineResponse2012);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('loginGuestPOST', function() {
        it('should call loginGuestPOST successfully', function(done) {
          // TODO: uncomment, update parameter values for loginGuestPOST call and complete the assertions
          /*

          instance.loginGuestPOST(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(DropBearTable.InlineResponse2003);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('loginPOST', function() {
        it('should call loginPOST successfully', function(done) {
          // TODO: uncomment, update parameter values for loginPOST call and complete the assertions
          /*

          instance.loginPOST(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(DropBearTable.InlineResponse2003);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('signupPOST', function() {
        it('should call signupPOST successfully', function(done) {
          // TODO: uncomment, update parameter values for signupPOST call and complete the assertions
          /*

          instance.signupPOST(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(DropBearTable.InlineResponse2011);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('userIdNotificationGET', function() {
        it('should call userIdNotificationGET successfully', function(done) {
          // TODO: uncomment, update parameter values for userIdNotificationGET call
          /*

          instance.userIdNotificationGET(userId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('userIdReservationGET', function() {
        it('should call userIdReservationGET successfully', function(done) {
          // TODO: uncomment, update parameter values for userIdReservationGET call and complete the assertions
          /*

          instance.userIdReservationGET(userId, reservationId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(DropBearTable.InlineResponse201);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('userIdReservationsGET', function() {
        it('should call userIdReservationsGET successfully', function(done) {
          // TODO: uncomment, update parameter values for userIdReservationsGET call and complete the assertions
          /*

          instance.userIdReservationsGET(userId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(DropBearTable.InlineResponse201);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('userIdReservationsPOST', function() {
        it('should call userIdReservationsPOST successfully', function(done) {
          // TODO: uncomment, update parameter values for userIdReservationsPOST call and complete the assertions
          /*

          instance.userIdReservationsPOST(body, userId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(DropBearTable.InlineResponse2012);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('userIdReservationsReservationIdDELETE', function() {
        it('should call userIdReservationsReservationIdDELETE successfully', function(done) {
          // TODO: uncomment, update parameter values for userIdReservationsReservationIdDELETE call and complete the assertions
          /*

          instance.userIdReservationsReservationIdDELETE(userId, reservationId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(DropBearTable.InlineResponse2004);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('userIdReservationsReservationIdPUT', function() {
        it('should call userIdReservationsReservationIdPUT successfully', function(done) {
          // TODO: uncomment, update parameter values for userIdReservationsReservationIdPUT call and complete the assertions
          /*

          instance.userIdReservationsReservationIdPUT(body, userId, reservationId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(DropBearTable.InlineResponse2012);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
